CREATE TABLE BOOKS (
	BOOK_ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(100) NOT NULL,
	AUTHOR VARCHAR(50),
	GENRE VARCHAR(50),
	PUBLISH_YEAR INT,
	PRICE NUMERIC(100, 2),
	STOCK INT
);

CREATE TABLE CUSTOMERS (
	CUSTOMER_ID SERIAL PRIMARY KEY,
	NAME CHAR(100) NOT NULL,
	EMAIL VARCHAR(100),
	PHONE NUMERIC(10),
	CITY VARCHAR(50),
	COUNTRY CHAR(50)
);

CREATE TABLE ORDERS (
	ORDER_ID SERIAL,
	CUSTOMER_ID SERIAL,
	BOOK_ID INT,
	ORDER_DATE DATE,
	QUANTITY INT,
	TOTAL_AMOUNT NUMERIC(100, 2)
);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (BOOK_ID);

SELECT
	*
FROM
	BOOKS;

SELECT
	*
FROM
	CUSTOMERS;

SELECT
	*
FROM
	ORDERS;

ALTER TABLE BOOKS
RENAME PUBLISH_YEAR TO PUBLISHED_YEAR;

COPY BOOKS (
	BOOK_ID,
	TITLE,
	AUTHOR,
	GENRE,
	PUBLISHED_YEAR,
	PRICE,
	STOCK
)
FROM
	'D:\Downloads D\Books.csv' CSV HEADER;

COPY CUSTOMERS (CUSTOMER_ID, NAME, EMAIL, PHONE, CITY, COUNTRY)
FROM
	'D:\Downloads D\Customers.csv' CSV HEADER;

ALTER TABLE CUSTOMERS
ALTER COLUMN COUNTRY TYPE CHAR(150);

COPY ORDERS (
	ORDER_ID,
	CUSTOMER_ID,
	BOOK_ID,
	ORDER_DATE,
	QUANTITY,
	TOTAL_AMOUNT
)
FROM
	'D:\Downloads D\Orders.csv' CSV HEADER;

-- 1) Retrieve all books in the "Fiction" genre:
SELECT
	*
FROM
	BOOKS
WHERE
	GENRE = 'Fiction';

-- 2) Find books published after the year 1950:
SELECT
	*
FROM
	BOOKS
WHERE
	PUBLISHED_YEAR > '1950';

-- 3) List all customers from the Canada:
SELECT
	*
FROM
	CUSTOMERS
WHERE
	COUNTRY = 'Canada';

-- 4) Show orders placed in November 2023:
SELECT
	*
FROM
	ORDERS
WHERE
	ORDER_DATE BETWEEN '2023-11-01' AND '2023-11-30';

-- 5) Retrieve the total stock of books available:
SELECT
	SUM(STOCK) AS TOTAL_AVAILABLE_STOCKS
FROM
	BOOKS;

-- 6) Find the details of the most expensive book:
SELECT
	*
FROM
	BOOKS
ORDER BY
	PRICE DESC
LIMIT
	1;

-- 7) Show all customers who ordered more than 1 quantity of a book:
SELECT
	C.CUSTOMER_ID,
	C.NAME,
	O.BOOK_ID,
	O.QUANTITY
FROM
	CUSTOMERS C
	INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE
	O.QUANTITY > 1;

-- 8) Retrieve all orders where the total amount exceeds $20:
SELECT
	*
FROM
	ORDERS
WHERE
	TOTAL_AMOUNT > 20
ORDER BY
	TOTAL_AMOUNT DESC;

-- 9) List all genres available in the Books table:
SELECT DISTINCT
	GENRE
FROM
	BOOKS;

-- 10) Find the book with the lowest stock:
SELECT
	*
FROM
	BOOKS
ORDER BY
	STOCK DESC;

-- 11) Calculate the total revenue generated from all orders:
SELECT
	SUM(TOTAL_AMOUNT) AS T_AMOUNT
FROM
	ORDERS;

-- 1) Retrieve the total number of books sold for each genre:
SELECT
	B.GENRE,
	SUM(O.QUANTITY) AS TOTAL_BOOKS_SOLD
FROM
	ORDERS O
	INNER JOIN BOOKS B ON B.BOOK_ID = O.BOOK_ID
GROUP BY
	B.GENRE;

-- 2) Find the average price of books in the "Fantasy" genre:
SELECT
	AVG(PRICE) AS AVG_PRICE
FROM
	BOOKS
WHERE
	GENRE = 'Fantasy';

-- 3) List customers who have placed at least 2 orders:
SELECT
	C.NAME,
	C.EMAIL,
	C.PHONE,
	O.QUANTITY
FROM
	CUSTOMERS C
	INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE
	O.QUANTITY >= 2
ORDER BY
	QUANTITY ASC;

-- 4) Find the most frequently ordered book:
SELECT
	B.TITLE,
	B.AUTHOR,
	B.GENRE,
	O.ORDER_DATE AS RECENT_ORDER
FROM
	BOOKS B
	INNER JOIN ORDERS O ON B.BOOK_ID = O.BOOK_ID
ORDER BY
	ORDER_DATE DESC
LIMIT
	1;

-- 5) Show the top 3 most expensive books of 'Fantasy' Genre :
SELECT
	*
FROM
	BOOKS
WHERE
	GENRE = 'Fantasy'
ORDER BY
	PRICE DESC
LIMIT
	3;

-- 6) Retrieve the total quantity of books sold by each author:
SELECT
	B.AUTHOR,
	SUM(O.QUANTITY) AS TOTAL_QUANTITY
FROM
	BOOKS B
	JOIN ORDERS O ON B.BOOK_ID = O.BOOK_ID
GROUP BY
	B.AUTHOR
ORDER BY
	TOTAL_QUANTITY DESC;

-- 7) List the cities where customers who spent over $30 are located:
SELECT
	C.NAME,
	C.CITY,
	C.COUNTRY,
	O.TOTAL_AMOUNT
FROM
	CUSTOMERS C
	JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE
	O.TOTAL_AMOUNT >= 30
ORDER BY
	TOTAL_AMOUNT ASC;

-- 8) Find the customer who spent the most on orders:
SELECT
	C.NAME,
	C.CITY,
	C.COUNTRY,
	O.TOTAL_AMOUNT
FROM
	CUSTOMERS C
	JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
ORDER BY
	TOTAL_AMOUNT DESC
LIMIT
	1;

--9) Calculate the stock remaining after fulfilling all orders:
SELECT
	B.BOOK_ID,
	B.TITLE,
	B.STOCK,
	COALESCE(SUM(O.QUANTITY), 0) AS ORDER_QUANTITY,
	B.STOCK - COALESCE(SUM(O.QUANTITY), 0) AS REMAINING_QUANTITY
FROM
	BOOKS B
	LEFT JOIN ORDERS O ON B.BOOK_ID = O.BOOK_ID
GROUP BY
	B.BOOK_ID
ORDER BY
	B.BOOK_ID;
